### root access
GET http://localhost:8000

###  login api end point
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email":"amrittsapkota32@gmail.com",
    "password":"123456"
}


### user router
###get user by id
GET http://localhost:8000/api/v1/user/ 
Authorization: 



### create user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "email":"amrittsapkota32@gmail.com",
    "password":"123456",
    "fName":"amrita",
    "lName":"sapkota",
    "role":"admin"
}


###tokrn endpoint 
# request fresh acessJWT
GET http://localhost:8000/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtcml0c2Fwa290YTMyQGdtYWlsLmNvbSIsImlhdCI6MTYxOTQ4NzI3NiwiZXhwIjoxNjIyMDc5Mjc2fQ.4VX9Ykhqs8MLngpNe3VAa4ZM_u6PP6IXI03qsDYxgCc



### Category Zone 
###  Fetch all category api end point
GET http://localhost:8000/api/v1/category

###  Fetch all category api end point
POST  http://localhost:8000/api/v1/category
Content-Type: application/json

{
  "name": "sds",
  "parentCategory": "dsd"
}
###patch 
PATCH   http://localhost:8000/api/v1/category
Content-Type: application/json

{
  "_id":"607a0e6c0aff1b12ec459683",
  "name": "sds"
 
}
### Delete ccate
DELETE   http://localhost:8000/api/v1/product/607e44eb585df81338aa29b4


### product zone

###  Fetch all product api end point
GET http://localhost:8000/api/v1/product

###  Fetch single product api end point
GET http://localhost:8000/api/v1/product/607b90e377a549394412c99c



POST  http://localhost:8000/api/v1/product
Content-Type: application/json

{
  "name":"dasdasdas",
  "qty":2
}

### fetch sinfgle product
PUT http://localhost:8000/api/v1/product
Content-Type: application/json

{
 "_id":"607b66567eaba54628b2453a"
 }
